rethinkdb/rethinkdb

- NOTES.md
@mglukhovsky @danielmewes @chipotle Could you please review?
> v1.15.3 release notes

- src/clustering/administration/main/command_line.cc
- src/rdb_protocol/terms/db_table.cc
I encountered this when compiled with `-Werror=maybe-uninitialized` option.
This change fix the build error.
> fix build error when `-Werror=maybe-uninitialized` is used

- NOTES.md
These notes cover all the issues that were closed in the 1.16 milestone on 2015-01-07 2:15 UTC.
@chipotle or @mglukhovsky, could you please review my writing?
@danielmewes and everyone else, could you please check that nothing important is missing and that the issues are correctly described?
> 1.16.0 release notes

- NOTES.md
https://github.com/rethinkdb/rethinkdb/issues/3694 is probably also going to make it into the release.
@mglukhovsky can you do a quick check please?
> Add #3694 to 1.16 release notes.

- drivers/ruby/lib/func.rb
- drivers/ruby/lib/net.rb
- drivers/ruby/lib/rpp.rb
- test/rql_test/cfeed_union.rb
- test/rql_test/drivers/driver.rb
- test/rql_test/server_test.rb
Link to style guide - https://github.com/bbatsov/ruby-style-guide#no-case-equality
> refactor class check in ruby driver

- drivers/python/rethinkdb/_export.py
This time the change is more in line with the code from _import.py
Perhaps this could be applied to the v1.16.x branch too...
> export: expose csv module's "delimiter" param

- NOTES.md
Ping @danielmewes @mglukhovsky
> Draft NOTES for 2.0.0~RC1

- NOTES.md
@danielmewes can you please review?
> 2.0.1 release notes

- src/rdb_protocol/ql2.proto
Discussed in https://github.com/rethinkdb/rethinkdb/issues/4151
> Update ql2.proto docs with option for order_by

- drivers/ruby/lib/net.rb
The Ruby driver network writes can potentially span multiple socket #syswrite calls, leading to interleaved packet data.  Making the send method atomic appears to make the client thread-safe, at least for inserts.
See issue #2911.
> Make Ruby driver network writes atomic

- NOTES.md
@mglukhovsky and @AtnNn could you please review?
> Release notes for 2.0.2

- NOTES.md
@danielmewes @mglukhovsky could you please review?
> Release notes draft for 2.0.3

- NOTES.md
@mglukhovsky @AtnNn could you review please?
> 2.0.4 release notes

- drivers/javascript/ast.coffee
- drivers/python/rethinkdb/ast.py
- test/rql_test/src/arity.yaml
> Make `<bool>.branch(...)` work

- NOTES.md
@danielmewes @mglukhovsky Could you please review?
> Draft release notes for 2.1-beta

- drivers/python/rethinkdb/_import.py
On a big file the buffer is not sufficient. I add argument parameter to change it.
I add too for the chunk size to accelerate import on big file
> make json buffer and chunk size as argument parameters #4451

- README.md
Fixed the community link  to http://rethinkdb.com/community and changed Twitter link to https
> Fixed the community link in the Need Help section

- admin/static/coffee/dashboard/panels.coffee
> Was using the wrong field-name for index panel

- README.md
Not sure why these two were left behind.
> Removing authors of community drivers

- drivers/ruby/lib/net.rb
Otherwise, there is no way to distinguish an empty stream, and a connection that has closed prematurely from the point of view of the handler.
> Signal error before closing EM handles abruptly

- NOTES.md
A first draft for the 2.1.0 release notes, updated from the 2.1.0 beta release notes.
There are still some missing parts (marked with "TODO").
@AtnNn you might also want to take a look.
>  2.1.0 release notes draft

- NOTES.md
The fix for #4664 probably won't make it in. I'll remove it from the release notes before merging in that case.
> 2.1.1 release notes

- drivers/ruby/lib/shim.rb
This issue dealt with a similar item #2284 however it did not resolve for rails 3.2.13.
Added this small fix to deal with that.
> added a as_json method to deal with bitop appearances in Rails 3.2.13

- drivers/python/rethinkdb/ast.py
- drivers/python/rethinkdb/net.py
This is my proposed solution for #3506 and #4569
> Create a JSON decoder subclass with a hook for pseudo types.

- NOTES.md
@dalanmiller or @AtnNn could one of you review these please?
> RethinkDB 2.1.3 release notes

- NOTES.md
@mglukhovsky or @dalanmiller could you review please?
> 2.1.4 Release notes draft

- NOTES.md
> 2.1.5 release notes

- README.md
Adding slack info to the readme.
@dalanmiller -- could you review?
> Adding slack to readme

- src/clustering/administration/main/command_line.cc
Update `--server-name` explanation text in the output of `--help`
> Resolve #4739

- drivers/python/rethinkdb/ast.py
- drivers/python/rethinkdb/net.py
- drivers/python/rethinkdb/net_asyncio.py
- drivers/python/rethinkdb/net_tornado.py
- drivers/python/rethinkdb/net_twisted.py
> Simple JSON override interface

- NOTES.md
@AtnNn or @mglukhovsky do you have time to review this quickly?
I'd like to start building tonight, or at least tomorrow morning.
> 2.2.1 release notes

- drivers/python/rethinkdb/_import.py
- drivers/python/rethinkdb/_restore.py
Fixes #5140. Haven't had a chance to test this yet, though.
> Add shard/replica parameters to `rethinkdb restore|import`

- NOTES.md
> Release notes for 2.2.2

- NOTES.md
@mglukhovsky can you review this please?
> RethinkDB 2.2.3 release notes

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rethinkdb/rethinkdb/5246)
> Update the number of official clients in README.md

- test/rql_test/src/aggregation.yaml
> Add Ruby variants to polyglot tests from #4846

- NOTES.md
We're going to retag 2.2.3 to include a few additional fixes.
> Updated 2.2.3 release notes

- drivers/java/src/main/java/com/rethinkdb/ast/Query.java
> Fix logging syntax

- README.md
> Adds new C# driver to README.md

- NOTES.md
> Release notes for 2.2.4 and 2.1.6

- drivers/python/rethinkdb/ast.py
> Refactored args attribute in RQLQueries (python driver)

- drivers/java/src/main/java/com/rethinkdb/net/Response.java
> Response is a feed if any note indicates a feed

- drivers/java/src/main/java/com/rethinkdb/net/SocketWrapper.java
Alternative fix for https://github.com/rethinkdb/rethinkdb/pull/5355
> Fix recvall method in Java driver

- drivers/javascript/cursor.coffee
- test/rql_test/connections/cursor.mocha
Refactor of [nighelles/5056](https://github.com/rethinkdb/rethinkdb/compare/nighelles/5056). See #5056.
> Simplified implementation of new `eachAsync`

- NOTES.md
> 2.2.5 release notes

- drivers/javascript/package.json
The old description was a bit misleading I think.
@dalanmiller or @mglukhovsky could you review please?
> Updated NPM package description

- drivers/java/src/main/java/com/rethinkdb/net/Connection.java
> Fixes resource leak in Java driver

- drivers/java/src/main/java/com/rethinkdb/net/Connection.java
Fixes #5468 
ping @danielmewes for review
> Java Connection implements Closeable

- packaging/assets/init/rethinkdb
> remove extra white space from rethinkdb init file

- NOTES.md
@mglukhovsky Could you review please?
> RethinkDB 2.2.6 release notes

- NOTES.md
@mglukhovsky can you review please?
> RethinkDB 2.3.0 release notes

- drivers/python/rethinkdb/_import.py
> Pass 'quiet' option to table_check method

- drivers/javascript/net.coffee
- drivers/javascript/rethinkdb.coffee
Hey,
PR for #5758 - one question though. I couldn't find any unit/integration tests, did I miss something?
> chore(modules): exposing the net class

- src/rdb_protocol/terms/sort.cc
- src/rdb_protocol/terms/writes.cc
This request is for issues - [#4656](https://github.com/rethinkdb/rethinkdb/issues/4656) and [#4615](https://github.com/rethinkdb/rethinkdb/issues/4615)
> Updated error message for Update query

- NOTES.md
> 2.3.3 release notes

- NOTES.md
> 2.3.4 release notes

- drivers/java/src/main/java/com/rethinkdb/net/SocketWrapper.java
Fixes #5841. [Ported from the C# driver.](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/SocketWrapper.cs#L42)
:car: :blue_car: [***"Let the good times roll..."***](https://www.youtube.com/watch?v=7BDBzgHXf64)
> Java Driver: Fixes #5841. Reset handshake!

- drivers/java/src/main/java/com/rethinkdb/net/Cursor.java
- drivers/java/src/test/java/com/rethinkdb/RethinkDBTest.java
Fixes #5468.
@danielmewes Please review!
> Java Cursor implements Closeable

- drivers/java/README.md
Fix link to javadoc.
This fixes #5898.
> Fixed javadoc link.

- mk/support/pkg/jemalloc.sh
- mk/support/pkg/protobuf.sh
> fix jemalloc for systems with /lib64 library paths

- NOTES.md
@mglukhovsky or @dalanmiller, could you review please?
> RethinkDB 2.3.5 release notes

- drivers/java/src/main/java/com/rethinkdb/net/Cursor.java
> Guard against calling .iterator twice on a Cursor

- .gitignore
- drivers/java/build.gradle
- drivers/java/src/main/java/com/rethinkdb/RethinkDB.java
- drivers/java/src/main/java/com/rethinkdb/ast/Util.java
- drivers/java/src/main/java/com/rethinkdb/converter/id.java
- drivers/java/src/main/java/com/rethinkdb/net/Util.java
- drivers/java/src/test/java/com/rethinkdb/TestingFramework.java
Now uses Jackson (Json parser)  for the java driver
> Java - Jackson

- README.md
Puts some build instructions info from RethinkDB's website into the README.md, where people tend look for it.
> Put build intructions into README.md.

- src/rdb_protocol/terms/random.cc
> limit sample size to array size limit

- src/containers/optional.hpp
Fixes two style problems that scripts/check-style.sh complained about.
> Fix linter complaints in optional.hpp

- NOTES.md
- src/concurrency/rwlock.cc
- src/concurrency/rwlock.hpp
- src/rdb_protocol/artificial_table/artificial_table.cc
- src/rdb_protocol/artificial_table/artificial_table.hpp
- src/rdb_protocol/datum_stream.hpp
- src/rdb_protocol/real_table.cc
- src/rdb_protocol/terms/random.cc
Cherry-pick a few fixes from `next` and add release notes draft.
> Potential v2.3.6 release candidate

- NOTES.md
- Updated a typo in `NOTES.md`
- Updated blog link in `NOTES.md`
- Added note about new license in `NOTES.md`
> update typo and links in NOTES.md

- mk/support/pkg/zlib.sh
> Update zlib version to 1.2.11

- src/pprint/js_pprint.cc
> Fix argument order in pretty-printed query

- mk/packaging.mk
> Use GCC 5 on Yakkety

- configure
- mk/support/pkg/node.sh
- mk/support/pkg/v8.sh
- src/arch/runtime/context_switching.cc
- src/client_protocol/json.cc
- src/client_protocol/server.cc
- src/rdb_protocol/datum.cc
- src/rpc/connectivity/cluster.cc
- src/unittest/print_secondary.cc
- src/unittest/rdb_interruptor.cc
- src/unittest/unittest_utils.cc
- src/unittest/unittest_utils.hpp
(I think the CLA has been signed on my and Rishi's (@rposts here) behalf by an IBM representative. Let me know if this isn't your understanding).
This adds support for Linux on z (s390x). A couple of open questions:
* Is it worth splitting up the context switching change (bcd07c8) into two commits? I've modified some of the comments to (hopefully) make what is going on a bit clearer as ports are added. I can break that out separately if you want to review it independently.
* Updating V8 to the lastest version for all non-Windows OSs would remove the need to pull in a s390x-specific version of it in 9f83100. We gave it a go but are seeing compilation errors. Are you planning on updating V8 at some point?
Thanks!
> Add Linux on z support (s390x)

- README.md
> Link to the Rust driver

- NOTES.md
> Add #6240 to release notes

- test/common/http_support/server.py
- test/rql_test/connections/r_http.py.httpbin
- test/rql_test/src/regression/6108.yaml
Some small fixes for various RQL tests so they can run.
> v2.4.x tests fixes

- src/clustering/administration/issues/outdated_index.cc
- src/rdb_protocol/pseudo_time.cc
- src/rdb_protocol/pseudo_time.hpp
- src/rdb_protocol/terms/string.cc
- src/rdb_protocol/terms/time.cc
- src/unittest/print_secondary.cc
- src/version.hpp
- test/rql_test/src/times/constructors.yaml
> Fix millisecond truncation rounding bug.

- mk/packaging.mk
My previous changes were just completely broken.
> Really fix Debian and Ubuntu packaging configuration

- README.md
This adds the C++ driver to the Readme.
> Adds Cpp driver

- NOTES.md
> cherry-pick release notes for v2.3.6 into next

- mk/packaging.mk
> Update deb packaging for bionic

- scripts/visualize_btree.py
<Please fill in the description of your pull request here. Thank you for your contribution!>
convert some print to python3 format
> convert print to python3 format

- src/clustering/administration/auth/permissions.cc
- src/clustering/administration/auth/permissions.hpp
- src/clustering/administration/auth/permissions_artificial_table_backend.cc
- src/clustering/administration/auth/user.cc
- src/clustering/administration/auth/user_context.cc
- src/clustering/administration/main/version_check.cc
- src/clustering/administration/tables/db_config.cc
- src/clustering/administration/tables/split_points.cc
- src/clustering/query_routing/table_query_client.cc
- src/containers/archive/archive.hpp
- src/containers/archive/boost_types.hpp
- src/containers/tribool.hpp
- src/rdb_protocol/changefeed.cc
- src/rdb_protocol/configured_limits.cc
- src/rdb_protocol/env.cc
- src/unittest/geo_indexes.cc
- src/unittest/rdb_env.cc
- src/unittest/rdb_protocol.cc
- src/unittest/unittest_utils.cc
Cherry-picks boost::tribool removal, including @robertjpayne 's bugfix commit.
> Cherry-pick tribool fix into 2.3.x

- src/btree/keys.cc
- src/btree/keys.hpp
- src/concurrency/new_mutex.hpp
- src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc
- src/unittest/clustering_utils_raft.hpp
Silences some warnings seen in Clang 8.
> Silence warnings

- README.md
This PR addresses a minor grammar issue in the README.
> README.md: minor copy edit

- admin/static/coffee/tables/index.coffee
Thanks to a report and some information from Hiroyuki Fujiwara
I'll note that the `db("name").ne(system_db)` part of the query is unnecessary.
> Improve web ui #table behavior for case with many db's

- NOTES.md
- mk/packaging.mk
- packaging/osx/create_dmg.py
> v2.4.x packaging config fixes and release NOTES.md draft

- README.md
> Free tommy li patch 2

- drivers/javascript/package.json
Updated the package.json to replace HTTP urls with HTTPS ones, and bump the version number.
Tested the JS driver and it works with the get/set write hooks
> Update package json and bump version number

- NOTES.md
Extend the release notes with a link to python driver release notes and bitwise operations.
> Extend release notes

- .circleci/config.yml
- src/clustering/administration/persist/file.hpp
- src/crypto/hmac.cc
Adding CircleCI config to make sure the code style, integration and unit tests are running. Please note that rql tests are not in scope right now since the drivers should be extracted and polyglot/rql tests should be handled somehow differently.
Also, at this moment unit and integration tests are failing.
Fixes https://github.com/rethinkdb/rethinkdb/issues/6840
> Add CircleCI config and fix styling issues

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Recommended community standards: [https://opensource.guide/](https://opensource.guide/)
* License must be Apache 2.0
* Code of conduct must be set
* Contributing guidelines must be set
* Remove .github directory if exists
* The .github folder must contain necessary files
<Please fill in the description of your pull request here. Thank you for your contribution!>
> Implement community standards

- NOTES.md
Release notes are not updated.
Collect the changes since the last release and update the release notes.
**Code examples**
N/A
**Checklist**
**References**
N/A
> Update release notes

- packaging/assets/config/default.conf.sample
- packaging/assets/init/rethinkdb
* improved and leveled out some comments
Nothing fancy, I just edited the start script and made some improvements to comments that might be nice to have in the main branch as well.
**Checklist**
> Improved comments in start script

- src/build.mk
I haven't yet tested this on Windows; I've only tested it on Linux.
> Integrate c-smile/quickjspp (for Windows support)

- configure
- src/arch/runtime/event_queue/kqueue.cc
- src/build.mk
- src/clustering/administration/persist/migrate/migrate_v1_14.cc
- src/rdb_protocol/geo/s2/base/port.h
- src/rpc/semilattice/semilattice_manager.tcc
Fixes compilation and some warnings on MacOS.
**Checklist**
> MacOS fixups

- src/extproc/js_job.cc
Uses QuickJS's JS_RunGC every 128 runs, just as we did with v8.  I didn't rethink the choice of 128 as the constant.
**Checklist**
> Use JS_RunGC to force quicker cleanup as we did with v8

- src/build.mk
> Point to QuickJS without function pointer warning

- mk/packaging.mk
- mk/support/build.mk
- mk/support/pkg/curl.sh
- mk/support/pkg/jemalloc.sh
- mk/support/pkg/libidn.sh
- mk/support/pkg/openssl.sh
Some explanation on updates and non-updates given here: 
https://github.com/rethinkdb/rethinkdb/issues/6975#issuecomment-1063654174
Tested on centos7, almalinux 8, alpine (runs into existing musl issue), archlinux, centos7, bionic, focal, hirsute, impish, jammy, xenial, buster, bullseye, jessie, stretch.
**Checklist**
> Update package versions

- src/arch/runtime/coroutines.cc
- src/arch/runtime/event_queue.cc
- src/arch/runtime/event_queue.hpp
- src/arch/runtime/event_queue/epoll.cc
- src/arch/runtime/event_queue/kqueue.cc
- src/arch/runtime/event_queue/poll.cc
Fixes #7044 and seems to fix #7041.
**Checklist**
> Make perfmons work with different n_threads values in multiple unit tests

- .circleci/config.yml
- configure
- test/rql_test/importRethinkDB.rb
- test/rql_test/test-runner
Implement some fixes to automatically run Ruby tests.
> Run ruby tests in circle ci

- packaging/assets/config/default.conf.sample
* leveled out some comments in `default.conf.sample`
Nothing fancy, just improved some comments in `default.conf.sample`
**Checklist**
> Minor improvement in configuration sample file

- README.md
> Apply tweaked README from next branch

- NOTES.md
> v2.4.2 release notes

- NOTES.md
> Update NOTES.md for 2.4.3

- admin/static/js/reql_docs.js
Issue has described in #6940 . Resolved by updating the links.
> Updated reql_docs link

- mk/support/pkg/zlib.sh
The website started returning 200 OK on its 404 page.
- [ x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/
> Replace bad zlib URL with backup url, use https

- README.md
> Put canonical location in old_admin build instructions
