rethinkdb/rethinkdb

drivers/javascript/net.coffee

`timeout` configuration option has no effect in case of connection refused error (server down). Timeout is cleared in `@rawSocket.once` and no error ever emitted. Since `@rawSocket.on "close"` event is called directly after `@rawSocket.on "error"` we can just emit a connection error.

javscript: Emit connection error

---

drivers/javascript/package.json

If bluebird releases a version 3, then a breaking change was introduced, and there's a good chance your entire driver could break. Luckily, the maintainer of bluebird is actually good so I doubt this would actually happen.

node: use semver correctly

---

drivers/ruby/lib/exc.rb

It's first Pull Request on refactoring ruby adapter – follow style guide for [single-line format for class definitions with no body](https://github.com/bbatsov/ruby-style-guide#single-line-classes)

Follow ruby style guide

---

drivers/ruby/lib/net.rb

Currently it does not work in this case
```ruby
r.connect('host' => 'localhost', 'port' => 28015)
```
because keys of config are String.
I suggest to convert the keys to Symbol.
It useful for case if connection config is located in yaml file, for example
```ruby
r.connect YAML.load_file('config/database.yml')
```
and `config/database.yml` is
```yaml
db: 'test'
host: '127.0.0.1'
port: 28015
```

config options with keys as String

---

drivers/ruby/lib/net.rb

`self` is only required when calling a self write accessor [link](https://github.com/bbatsov/ruby-style-guide#no-self-unless-required)

Avoid self where not required

---

src/protob/protob.cc

Write `SUCCESS\0` after verifying protocol magic number.

---

drivers/javascript/ast.coffee
drivers/javascript/util.coffee

In a few spots the JavaScript driver uses `instanceof` to check for array, function, and object types. As `instanceof` looks at the variable's prototype to find the appropriate constructor, this is a problem when checking a variable that was instantiated in a different JavaScript context, such as an iframe, or in this case the Node Webkit window context. See [Differences of JavaScript contexts](https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts).
Using `typeof` (or `Array.isArray` for arrays) is robust to cross-context type checking.
This PR changes three `instancesof` type checks to use `typeof` and one to use `Array.isArray`.
I ran the tests like so `/rethinkdb/test/rql_test/test-runner -i js` and they passed.

Fixes #4037

---

drivers/python/rethinkdb/net.py
drivers/python/rethinkdb/net_asyncio.py
test/rql_test/connections/asyncio_connection.py
test/rql_test/connections/asyncio_connection.py.test

This probably needs quite a bit of work, but it's working for a basic example, and I wanted to communicate early. @techdragon talked me into working on this at the PyCon sprints.
Asyncio is part of the standard library in Python 3.4. It's a rather similar API to tornado, so I copied and pasted the net_tornado code that's already in rethinkdb and modified it until it works. The syntax is only valid on Python 3, but the module shouldn't be imported until you do `r.set_loop_type('asyncio')`, so that shouldn't be a problem.
Here's the asyncio version of the tornado example from your [async drivers blog post](http://www.rethinkdb.com/blog/async-drivers/) (BTW, that example is missing a colon on the `while` line):
```python
import asyncio
import rethinkdb as r
r.set_loop_type("asyncio") …
```

Add asyncio event loop support

---

drivers/ruby/lib/net.rb

[Addresses Ruby Driver](https://github.com/rethinkdb/rethinkdb/issues/3158)
The following abstracts the socket connection out a bit to allow for creating an SSL connection to a cluster. In order for this to be used, you'd need a proxy (Haproxy, nginx, etc) sitting in front of the RethinkDB cluster performing the SSL verification.
For now, the SSL support is only good for encrypting traffic and verifying the CA certification to prevent MITM attacks.

[ruby] support for ssl encryption and CA verification

---

drivers/python/rethinkdb/net.py
drivers/python/rethinkdb/net_tornado.py

[Addresses Python Driver](https://github.com/rethinkdb/rethinkdb/issues/3158)
The following abstracts the socket connection out a bit to allow for creating an SSL connection to a cluster. In order for this to be used, you'd need a proxy (Haproxy, nginx, etc) sitting in front of the RethinkDB cluster performing the SSL verification.
For now, the SSL support is only good for encrypting traffic and verifying the CA certification to prevent MITM attacks. 
For the implementation, I'm using the additional kwargs to add `ssl` and `ca_certs`.

[python] support for ssl encryption and CA verification

---

src/rdb_protocol/ql2.proto

While implementing contains for https://github.com/hamiltop/exrethinkdb I found that the behavior of the function to differ from the spec.
1. Multiple predicates are allowed and behave as a logical `AND`
2. A mix of predicates and datum are allowed and behave as a logical `AND`
Number 1 is reflected in the actual docs properly but not reflected in the spec.
Number 2 is in neither the docs nor the comments in the spec.

Update proto doc for contains

---

drivers/javascript/net.coffee

[Addresses JavaScript Driver](https://github.com/rethinkdb/rethinkdb/issues/3158)
The following will use `tls.connect` when doing an SSL connection to a cluster. In order for this to be used, you'd need a proxy (Haproxy, nginx, etc) sitting in front of the RethinkDB cluster performing the SSL verification.
For now, the SSL support is only good for encrypting traffic and verifying the CA certification to prevent MITM attacks. 
For the implementation, I'm using additional `r.connect` options: `ssl` and `sslCaCerts` so a connection would look like the following:
```javascript
r.connect({ host: 'localhost',
port: 28015,
db: 'marvel',
authKey: 'hunter2' },
ssl: true,
sslCaCerts: '/path/to/ca.crt'
function(err, conn) { ... })
```

[JS] support for ssl encryption and CA verification

---

src/serializer/buf_ptr.hpp

scoped_malloc_t already supports move semantic

remove redundant code

---

drivers/javascript/ast.coffee
test/rql_test/src/control.yaml

JS Driver: allow `r.js` to accept a function

---

drivers/javascript/ast.coffee
test/rql_test/src/control.yaml

Reverts rethinkdb/rethinkdb#4269 due to concerns that the interface will be confusing

Revert "JS Driver: allow `r.js` to accept a function"

---

drivers/javascript/net.coffee
test/rql_test/connections/connection.js

JS Driver: db optarg to `.run()` is ignored if default db is already set on the connection

---

admin/static/coffee/modals.coffee

Hi, I've recently found myself deleting some databases manually via the web interface and was annoyed that whitespace around the database name wasn't ignored. This PR fixes that.
Feel free to close if you think this is unnecessary. Btw, thanks for the amazing work so far!

Ignore whitespace in database delete confirmation

---

NOTES.md

Sorry I missed another issue that got fixed on v2.0.x in the meantime: https://github.com/rethinkdb/rethinkdb/issues/4473
This pull request adds it to the 2.0.4 release notes.

Added 4473 to 2.0.4 release notes

---

drivers/javascript/ast.coffee

IE 10 doesn't have the `__proto__` property. So for JS interpreters without `__proto__` we skip the `__proto__` magic (thereby disabling the `foo('bracket')` syntax in ReQL).
Fixes #162
Fix suggested by @mikemintz

Only set __proto__ in TermBase if it exists

---

admin/static/coffee/tables/index.coffee

changing the order of the if/else statement for rendering either the loading_databases or no_databases templates fixes issue 4464
https://github.com/rethinkdb/rethinkdb/issues/4464

switched order of if/else statement

---

src/rdb_protocol/func.cc
test/rql_test/src/control.yaml

#4189
check arity before calling passed in functions for `reduce`, `filter`, `concat_map`, `group`, `avg`, `min`, and `max`

check arity before calling passed in functions

---

NOTES.md

We're going to do two point releases, one on the 2.0 branch and one for 2.1.

RethinkDB 2.1.2 and 2.0.5 release notes

---

drivers/javascript/net.coffee

JS Driver 2.1.0 shipped with broken SSL functionality.
This fix corrects the missing variable and pre-populates TLS config options with the host and port from the rethinkdb host object.
Usage:
```javascript
var r = require( 'rethinkdb' );
r.connect({
host: 'aws-eu-west-1-portal.1.dblayer.com',
port: 10999,
authKey: 'XXXdYXnhUKUCXOG1ejodIHypwd9JTQOwO1CgmHSCXXX',
ssl: {
ca: [ fs.readFileSync(__dirname+'/part_to_public_key.crt') ]
}
}, function(err, conn) {
if(err) throw err;
console.log('connected');
});
```

Fix reference to options in TLS constructor (SSL)

---

drivers/java/src/test/java/RethinkDBTest.java

Hi @deontologician. Shadowing your progress on your Java driver with my C# driver and I think we need run here. :)
https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver.Tests/ConnectionTest.cs

Java Driver: Fixing dbCreate() to run

---

drivers/java/src/main/java/com/rethinkdb/net/Converter.java

I decided to try the Java driver, but the build failed it's testing! Tests produced many of these null pointer exceptions:
```
java.lang.NullPointerException
at java.util.HashMap.merge(HashMap.java:1216)
at java.util.stream.Collectors.lambda$toMap$230(Collectors.java:1320)
at java.util.stream.Collectors$$Lambda$28/1254557951.accept(Unknown Source)
at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) …
```

Java Driver: Change map collector to bypass HashMap.merge()

---

drivers/java/.gitignore
drivers/java/src/main/java/com/rethinkdb/ast/ReqlAst.java
drivers/java/src/test/java/RethinkDBTest.java
drivers/java/src/test/java/TestingFramework.java
drivers/java/src/test/resources/default-config.properties
drivers/java/test-config-override.properties

Hi,
here is a fix to the bug 4845 I just entered. I also upgraded the test class to allow "override" of the configuration without having to modify any code.
The idea is to include a file in the root of the java driver called "test-config-override.properties" that can contains the hostName and port parameters. This file is git-ignored so nobody commit it to the repo.
If not defined, those parameters default to "newton" and 31157 which are Josh's parameters, I guess.
Have a nice day !

Fix for 4845

---

drivers/python/rethinkdb/ast.py
drivers/python/rethinkdb/net.py
drivers/python/rethinkdb/net_asyncio.py
drivers/python/rethinkdb/net_tornado.py
drivers/python/rethinkdb/net_twisted.py

This makes the query encoding recurse one fewer times like the response improvement.

Implement a custom encoder to match the decode route.

---

admin/static/coffee/dataexplorer.coffee

Execute only highlighted portion of query in data explorer

---

drivers/javascript/cursor.coffee
test/rql_test/connections/cursor.mocha

Fixes #4780. Unfortunately, there was no way to implement this as an overload to the existing `cursor.each()` since there's no way to disambiguate the argument style.
Here's some example usage:
```js
cursor.eachAsync(function (row) {
if (/* some condition */) {
// if you return a promise, it will be awaited
// before the cursor continues iteration
return asyncRowHandler(row.id);
}
else {
// iteration can be stopped early by returning a
// promise that is later rejected or simply by throw'ing
return Promise.reject('Stop iteration early.')
}
})
.then(function () {
// `cursor.eachAsync()` returns a promise that is resolved
// once all rows have been read from the cursor
});
```

JS Driver: promise friendly `cursor.eachAsync()`

---

drivers/java/src/main/java/com/rethinkdb/ast/Util.java
drivers/java/src/main/java/com/rethinkdb/net/Converter.java
drivers/java/src/test/java/RethinkDBTest.java

Upstream implementation of Date-to-ReqlAst conversion causes a precision loss: seconds and milliseconds are gone. The conversion of value returned from database also causes milliseconds to be lost, because the double value is truncated before it's multiplied by 1000.
Fixed both issues and added a test.

Date precision loss in Java driver

---

drivers/java/templates/ast/Funcall.java

For @deontologician ,
After some protocol debugging in the C# driver, it appears the Java driver is also affected. Per the Python source code:
```
class FunCall(RqlQuery):
tt = pTerm.FUNCALL
def __init__(self, *args):
if len(args) == 0:
raise ReqlDriverError("Expected 1 or more arguments but found 0.")
args = [func_wrap(args[-1])] + list(args[:-1])
.....
```
Seems like the actual wire-line format is function first, arguments last, so we flip them around when building the AST.
This PR adds a `Funcall` template that overrides `build()` moving the last argument to the first. It's been about 14 years since I wrote Java, so I hope this is correct. :)
This should also get a few more unit tests to pass.
P.S.: I tried to keep the PR as small as possible so the AST should get regenerated.

Java Driver: Fixes ordering of Funcall Arguments in the AST.

---

src/clustering/administration/tables/calculate_status.cc
src/clustering/administration/tables/calculate_status.hpp
src/clustering/administration/tables/table_status.cc
src/clustering/table_manager/table_meta_client.cc
src/clustering/table_manager/table_meta_client.hpp

This adds support for tracking the raft leader for each table and
displaying that information per-table in the table_status
artificial table.
relates to issue https://github.com/rethinkdb/rethinkdb/issues/4902
I know there probably is a lot to review here, as I'm clearly not very familiar with your code base. Off the top of my head I have the following comments/concerns:
* The serialized form of `table_status_response_t` has changed, making it incompatible with older versions of the database. I had considered packing this information into `table_raft_state_t` but wasn't sure if that would even make a difference, so it would be helpful if someone could advise here (I tacked it on to the end of the serialization in case order mattered here).
* The location of the data itself is just set as …

feat(raft_leader): display raft leader for table in table_status

---

drivers/javascript/ast.coffee
test/rql_test/connections/tostring.mocha

This addresses part of issue #2372.
Before this change:
> r.table('turtles', {readMode: 'single'}).toString()
'r.table("turtles", {readMode: "single"})'
> r.expr({'-x-y-z': 2}).merge({b: [1,2]}).toString()
'r({-x-y-z: "b"}).merge({b: [1, 2]})'
After this change:
> r.table('turtles', {readMode: 'single'}).toString()
'r.table("turtles", {"readMode": "single"})'
> r.expr({'-x-y-z': 2}).merge({b: [1,2]}).toString()
'r({"-x-y-z": "b"}).merge({"b": [1, 2]})'

Properly quote JS object keys in toString()

---

drivers/java/build.gradle
drivers/java/src/main/java/com/rethinkdb/ast/ReqlAst.java
drivers/java/src/main/java/com/rethinkdb/ast/Util.java
drivers/java/src/main/java/com/rethinkdb/net/Connection.java
drivers/java/src/main/java/com/rethinkdb/net/Cursor.java
drivers/java/src/main/java/com/rethinkdb/net/Util.java
drivers/java/src/test/java/RethinkDBTest.java
drivers/java/src/test/java/TestPojo.java
drivers/java/src/test/java/TestPojoInner.java

Added support for select and insert operations on Java bean classes, not only on boxed primitive types, lists and maps. You can select one typed object:
```java
Pojo pojo = r.db("db").table("table").get("reql-expr").run(conn, Pojo.class);
```
...or a list of objects:
```java
List<Pojo> pojoList = r.db("db").table("table").get("reql-expr").runList(conn, Pojo.class);
```
Objects are constructed from ```Map<String, Object>``` instances selected from RethinkDB using reflection. Insertion of typed objects employs the same technique:
```java
Pojo pojo = new Pojo("foo", new NestedPojo(42L, true));
r.db("db").table("table").insert(pojo).run(conn);
```
Merging this code to Java driver would be extremely useful for me and, I presume, to the community, because working with maps and primitives is …

Support for insert and select operations with POJOs in Java driver

---

drivers/java/src/test/java/RethinkDBTest.java

I wrote this test as a tiny workaround to the lack of Java driver docs mentioned [here](https://github.com/rethinkdb/rethinkdb/issues/3930#issuecomment-154913718). I hope it's worth adding to the driver code base.
I think that @deontologician is the appropriate assignee for this PR.

Added a test for the '.filter(...)' function in the Java driver

---

drivers/java/build.gradle

While evaluating the new Java driver, I found it easiest to publish to my local repo instead of trying to workaround via a remote snapshots repository. I think this will come in handy for others, especially Scala developers who use SBT and rely on local Ivy repo publication.

Allow for local publishing of both Ivy and Maven repos.

---

drivers/java/src/main/java/com/rethinkdb/ast/Query.java
drivers/java/src/main/java/com/rethinkdb/net/Connection.java

Using Integer.BYTES and Long.BYTES makes the intent of the byte handling
code clearer, and less error prone if there are future changes to these
sections.

Use Integer.BYTES and Long.BYTES instead of hardcoding size

---

drivers/javascript/ast.coffee

This is a rewrite of PR https://github.com/rethinkdb/rethinkdb/pull/4534 to resolve issue https://github.com/rethinkdb/rethinkdb/issues/162 (IE10 support in the JS driver).
The only difference is replacing `self` with `return self`. I'm not familiar with CoffeeScript, but it's now closer to the original code. The tests that were failing before are now passing for me.

Only set __proto__ in TermBase if it exists (attempt 2)

---

drivers/python/rethinkdb/_import.py

This is needed when you want to export and import some documents deeper than the default nesting depth limit of 20.

Support specifying a custom nesting depth to rethinkdb import

---

drivers/ruby/lib/net.rb

Ran across this earlier with the Ruby driver:
`Users/josh/.rbenv/versions/2.3.0-preview2/lib/ruby/gems/2.3.0/gems/rethinkdb-2.2.0.1/lib/net.rb:815:in `maybe_timeout': Object#timeout is deprecated, use Timeout.timeout instead.`
`#start_listener` in `net.rb` was making a call to `Object#timeout` which is [depreciated](http://ruby-doc.org/stdlib-2.1.0/libdoc/timeout/rdoc/Object.html). Per the depreciation notice, I switched the call over to `Timeout.timeout` and checked it once more to verify it was OK.
Here's my Rails Console output before and after this patch:
```
irb(main):001:0> User.create(:name => 'Nico')
/Users/josh/.rbenv/versions/2.3.0-preview2/lib/ruby/gems/2.3.0/gems/rethinkdb-2.2.0.1/lib/net.rb:815:in `maybe_timeout': Object#timeout is deprecated, use Timeout.timeout instead. …
```

`Object#timeout` is depreciated, updated to use `Timeout#timeout`

---

drivers/java/src/main/java/com/rethinkdb/net/Converter.java

When loading the java driver in Eclipse IDE 4.5.1 gives an error
```
The type HashMap does not define putAll(Object, Object) that is applicable here	Converter.java	/drivers-java/src/main/java/com/rethinkdb/net	line 67
```
Specifying an explicit  type argument fixes the problem.

fix a java compiler error in eclipse.

---

test/rql_test/README.md

Apparently you also need Python's Twisted to run RQL tests (at least it shouted at me running Ruby tests when I did not have it installed). This might be a useful information to add to RQL tests Readme.

Add information about Twisted requirement

---

drivers/python/setup.py

This adds links to the Python API documentation, GitHub project,
and Python driver source to setup.py's module docstring (formerly
missing), which is also now used as the package's long_description.
This makes https://pypi.python.org/pypi/rethinkdb more helpful to
users, and also guides potential contributors to the right place for
patches.

add long_description with missing important links

---

drivers/java/build.gradle

@deontologician with the release of `beta-2`, we should bump to `beta-3-SNAPSHOT`, right?

Bumped Java driver development version to 2.2-beta-3-SNAPSHOT.

---

drivers/java/src/main/java/com/rethinkdb/net/Response.java

Discovered in `C#/.NET` driver by inspection analyzers. #5390 related. `Cursor.isFeed` would still always be false.

Java: ResponseNotes was never used.

---

CONTRIBUTING.md
STYLE.md

I added our C++ coding style from the `company` repository . There is no reason it should not be available in the public repository as far as I can tell. I didn't make any changes to the file itself, except for replacing a recommendation to compare to `NULL` by one to compare to `nullptr` (which is what new code should be doing).
Once this is merged, I'm going to remove the copy on `company`.
@VeXocide would you mind doing a quick check that I'm not committing anything unreasonable?

Add C++ coding style document

---

drivers/javascript/ast.coffee

See https://github.com/rethinkdb/rethinkdb/issues/162 and https://github.com/rethinkdb/rethinkdb/pull/5067 for context.

Add missing return keyword in TermBase constructor

---

drivers/python/rethinkdb/_dump.py

This is useful when writing files tat have a fixed name,
that have file permissions already set, or file descriptors.

rethinkdb-dump: Add `--overwrite-file` option

---

drivers/java/src/main/java/com/rethinkdb/net/Response.java

`rethinkdb/drivers/java/src/main/java/com/rethinkdb/net/Response.java` output debug log server response, it unconditionally convert ByteBuffer to String, even if debug log is disabled.
```
public static Response parseFrom(long token, ByteBuffer buf) {
Response.logger.debug("JSON Recv: Token: {} {}", token, Util.bufferToString(buf));
```
So add a check is better.
```
if (Response.logger.isDebugEnabled())
Response.logger.debug("JSON Recv: Token: {} {}", token, Util.bufferToString(buf));
```

a trivial improve: limit unnecessary debug log string creation

---

drivers/python/rethinkdb/_dump.py
drivers/python/rethinkdb/_export.py
drivers/python/rethinkdb/_import.py
drivers/python/rethinkdb/_restore.py

This adds two features to `rethinkdb-dump`:
* A `--quiet` flag
* Writing the output archive to stdout
The second feature quite obviously depends on the first one, since we can't print messages and a tar archive to stdout at the same time.
The wording of the help option was inspired by `man tee`.
Example commands you can test:
* `rethinkdb-dump` - should work as before
* `rethinkdb-dump` - should work as before but print no output
* `rethinkdb-dump --file=out.tar.gz` - should work as before
* `rethinkdb-dump --file=-` - should print lots of rubbish into your terminal
* `rethinkdb-dump --file=- | tar tz` should print you the files in the tar file

rethinkdb-dump: Add --quiet and dumping to stdout

---

drivers/python/rethinkdb/_restore.py

Fixes #5647 
Python 3's sys.stdin is not of type "file" anymore, but rather
_io.TextIOWrapper -- which parses down to just type Class (apparently)
This should fix python3, but also work in python2.
This might be a naive approach, but I don't really see another option. :fearful:

Fix for #5647

---

drivers/java/src/main/java/com/rethinkdb/net/Connection.java

Hola,
I think this PR will fix #5439 and fix #5660 for the Java driver.
The core of the bug is described here: https://github.com/rethinkdb/rethinkdb/issues/5660#issuecomment-210734741
The crux of the issue is that only `IOException` is being handled. If another exception type was thrown, the `ResponsePump` thread exceptionally exit without clean up and without notifying cursor changefeeds causing what looks like a stalled changefeed upon a server restart.
I'm not sure how I could write a unit test for this particular issue since it would require restarting the RethinkDB server :electric_plug: during a unit test.
All unit tests pass (except a few string tests). Probably because some M$ Windowz string quirks?

Java Driver PR: Fixes #5439 and Fixes #5660.

---

src/clustering/administration/main/command_line.cc
src/clustering/administration/main/serve.cc
src/clustering/administration/main/serve.hpp
src/clustering/administration/servers/auto_reconnect.cc
src/clustering/administration/servers/auto_reconnect.hpp

Currently the auto_reconnect instance used to reconnect lost nodes
is hardcoded to give up reconnecting after 24 hours. This is not
ideal in some scenarios where a user may want to remove a node from
a cluster, without having to reset all other participating nodes in
the cluster. This patch allows the user to change that value.

feat(auto_reconnect): allow runtime configuration of give_up_ms (v2)

---

drivers/ruby/lib/shim.rb

Ruby seems to add some garbage beyond the provided epoch_time resolution, which makes the read times be slightly after the originally saved times. This is specially evident when running tests.
```
2.2.4 :006 > Time.at(1463567776.592).iso8601(30)
=> "2016-05-18T12:36:16.592000007629394531250000000000+02:00"
2.2.4 :007 > Time.at(1463567776.592).round(3).iso8601(30)
=> "2016-05-18T12:36:16.592000000000000000000000000000+02:00"
```
This PR just rounds the times as shown in the code example above after reading them, removing the bogus microseconds.
PS: I'd love to write some tests, but to run the test suite I need to build the server, which is failing for me with an `npm` error 😢 (Currently it is breaking on `admin-deps_2.0.3` because `npm ERR! registry URL is required`) . Help would be …

Round the time values to the Rethinkdb precision

---

admin/static/js/codemirror/codemirror.js

Safari on OS X will try to spellcheck if spellcheck is not disabled on the CodeMirror textarea.
Fixes #5777

Disable spellcheck on CodeMirror input

---

drivers/python/rethinkdb/net.py

Added support for `with` statement in the python driver as mentioned in #5768. Now users will be able to run queries like:
```
with r.db('foo').table('bar').run(conn) as table:
for row in table:
pass
```

Added `with` support for Cursor in python driver

---

src/clustering/administration/logs/log_writer.cc

<Please fill in the description of your pull request here. Thank you for your contribution!>
This fixes an ambiguous message on the log_writer module whenever it tries to write a message to a log file , but the log_write module hasn't yet being initialized with a proper  log file.

This fix solves the ambiguous message displayed by the logger

---

drivers/python/rethinkdb/asyncio_net/net_asyncio.py

Hi,
This simply fixes a forgotten `yield from` syntax which would crash the driver when an Exception is raised.

fix: asyncio ConnectionInstance should yield from on Exception

---

drivers/javascript/net.coffee

Documented as `r.connect([options]) → promise`, but `options` is not optional, see #5846.

Fix issue #5846

---

drivers/ruby/lib/shim.rb

- [X ] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/
In ruby/rails -- storing a `Time.now.end_of_day` in rethink, always returns the next day
```
> d = Date.today
> d.to_time
=> 2016-06-03 00:00 +0000
> d.to_time.end_of_day
=> 2016-06-03 23:59 +0000
> d.to_time.end_of_day.to_i
=> 1464998399
> d.to_time.end_of_day.to_r
=> (1464998399999999999/1000000000)
> d.to_time.end_of_day.to_f
=> 1464998400.0     <--- The Problem
> ((d.to_time.end_of_day.to_r  * 1000).to_i / 1000.0)  <--- The Fix
=> 1464998399.999
```
Due to a rounding error with `.to_f`  
The fix ensures that the Time is truncated to milliseconds with no rounding error.

fix for rounding error with ruby times

---

drivers/java/src/main/java/com/rethinkdb/net/Cursor.java

Compliments of the C# driver. :bow:
To Java driver, From the C# driver, with love. :heart: 
Reference https://github.com/rethinkdb/rethinkdb/issues/5980
----
:sparkles: :point_left: [***"Hey, hey, do that brand new thing... Uh-huh, Uh-huh!"***](https://www.youtube.com/watch?v=AltMeuPkWRs)

Fixes #5980 - Java Driver: Remove Cursor from cursorCache on close()

---

drivers/java/src/main/java/com/rethinkdb/net/Connection.java
drivers/java/src/test/java/com/rethinkdb/RethinkDBTest.java

fix [hidden memory leak when close Changefeeds cursor · Issue \#6009](https://github.com/rethinkdb/rethinkdb/issues/6009)

Changefeeds cursor close cause new cursor cause memory leak

---

src/arch/address.cc
src/arch/address.hpp
src/clustering/administration/servers/auto_reconnect.cc
src/clustering/administration/servers/auto_reconnect.hpp
src/rpc/connectivity/cluster.cc
src/rpc/connectivity/cluster.hpp

This is a series of patches that aim to improve intra-cluster connections. This is primarily achieved by the following:
- Introduce a `join_result_t` enum in order to return meaningful results from `connectivity_cluster_t::run_t::join_blocking`. This allows for enabling certain behaviors based on that reuslt.
- One of those aforementioned behaviors is to stop retrying intra-cluster reconnects in the `auto_reconector_t` if a join has failed irrecoverably (a `join_result_t::PERMANENT_ERROR`) 
- Finally, a new `PERMANENT_ERROR` was introduced in the `run_t::handle` method: if an expected server id is provided, and the remote server's id does not equal that value upon initial handshake, then that will prevent further reconnects.
/cc @danielmewes

intra-cluster handshake improvements

---

mk/packaging.mk
packaging/debian/rules
src/build.mk

- Don't unnecessarily build the web assets when packaging.
- Don't build RethinkDB twice when building Debian and Ubuntu packages
- Ignore warnings in generated C++ files

Misc makefile fixes

---

src/unittest/rdb_interruptor.cc

Apparently these have been failing since write hooks were
implemented.
Disables failing tests.  We get a nice warning that they're disabled when you run unit tests.  All the other unit tests pass.
See #6095, which is the issue about the test failures.

Disable failing InsertOp and DeleteOp tests.

---

src/rdb_protocol/datum_stream.cc
src/rdb_protocol/datum_stream.hpp

don't persist stale env_t* in ordered unions

---

mk/support/pkg/zlib.sh

The currently used version was released in April 2013.

update zlib to 1.2.10

---

mk/support/pkg/zlib.sh

The archive was moved, the current URL is now a 404

fix zlib-1.2.8 source url

---

scripts/build-rpm.sh

<Please fill in the description of your pull request here. Thank you for your contribution!>
From a slack conversation with "@atnnn"
tennis [1:34 PM] 
Hi Guys. I’ve compiled the rethink rpm package on CentOS 7.3 successfully (using this script: https://github.com/rethinkdb/rethinkdb/blob/next/scripts/build-rpm.sh).  Everything compiles fine.  But when I go to use the rpm to install on *exactly* the same machine, I get this error:
```--> Finished Dependency Resolution
Error: Package: rethinkdb-2.3.5_11_ga3b90f-29875.x86_64 (/rethinkdb)
Requires: glibc >= 2.172.17
Installed: glibc-2.17-157.el7_3.1.i686 (@updates)
glibc = 2.17-157.el7_3.1
Available: glibc-2.17-157.el7.i686 (base)
glibc = 2.17-157.el7
```
Any ideas?
atnnn [2:19 PM] 
@tennis what is the result of `rpm -qa --queryformat …

fix: keep multiple libs from catenating versions

---

src/rdb_protocol/terms/string.cc

This fixes #6202 for `2.3.x`. #6203 fixes the issue in `next`.
Disabling the cache entirely is the safer option for a point release.

Disable broken regex cache

---

src/clustering/administration/persist/file.cc
src/clustering/administration/persist/migrate/migrate_v2_3.cc
src/clustering/administration/persist/migrate/migrate_v2_3.hpp

I signed it back in 2012 https://github.com/rethinkdb/rethinkdb/pull/57
This implements metadata migration from RethinkDB 2.3 metadata to version 2.4. It's fairly trivial: We just need to rewrite all metadata that contains `table_config_t`, since those have changed in 2.4. The deserialize method of `table_config_t` still supports reading the old format, so a simple rewrite suffices.
This fixes https://github.com/rethinkdb/rethinkdb/issues/6085 .
On a side note, I just fired up RethinkDB again for the first time in a few months to test this. And man, it's awesome! ReQL, the clustering, it's all a big joy to use. :) :(

Metadata migration for RethinkDB 2.4

---

src/arch/io/disk.cc
src/arch/io/disk.hpp
src/arch/types.hpp
src/serializer/log/extent_manager.cc
src/serializer/log/metablock_manager.cc
src/serializer/log/static_header.cc
src/unittest/mock_file.cc
src/unittest/mock_file.hpp

Instead of using DEFAULT_EXTENT_SIZE.  Note: All releases of RethinkDB
since 1.13 have had an extent size of 2.0 MB, with no option to
reconfigure.  (This is just a small code cleanup, don't read too much
into it.)

Make set_file_size_at_least take the real extent size.

---

src/containers/archive/tuple.hpp

Avoids complaint about zero size array.

Fix Windows build error with tuple serialization.

---

mk/support/pkg/pkg.sh

2.4.x and next store fetched tarballs in `external/.cache`. The CI server relies on this to avoid re-fetching dependencies and to isolate builds from the network.
This patch adds read-only support for the cache in 2.3.x

Use cached dependencies in 2.3.x

---

scripts/gen-version.sh

The current check uses `update-index`, which doesn't work if `.git` is read-only

Improve dirty check in gen-version

---

mk/support/pkg/jemalloc.sh

This change adds a space between the --libdir and --host arguments and removes the surrounding quotes so that the jemalloc configure script will process both options correctly.
Prior to this change, when cross compiling the jemalloc package, there was no space between the --libdir and --host arguments to the configure script and they were surrounded in quotes (causing the jemalloc configure script to fail with missing --host option).

jemalloc configure fails with missing --host option during cross compile

---

mk/support/pkg/node.sh

The version of Node.js in the 'latest' directory changes over time.
Switch to using the version-specific directory.
A new version of Node.js has been released and it has broken the link we were using. This change should fix that (and stop it happening again).

Fix Node.js fetch address.

---

src/clustering/administration/persist/file.cc
src/clustering/administration/persist/migrate/migrate_v2_1.cc

Two bugs.
1. The v2_1->v2_3 auth metadata migration was getting passed over.
All that "serialization_version" means in the function
migrate_metadata_v2_1_to_v2_3 is what version the structs were last
serialized at -- what cluster_version_t W parameter was used.  Auth
metadata _still_ needs to get migrated.
2. Because the v2_2 case in metadata_file_t::metadata_file_t did not
set metadata_version to the value cluster_version_t::LATEST_DISK, the
subsequent call to migrate_metadata_v2_3_to_v2_4 would hit
unreachable() in migrate_metadata_v2_3_to_v2_4.
This should also be cherry-picked into the v2.4.x branch and make it into v2.4.

Fix metadata migration for non-v2_3->v2_4.

---

mk/support/pkg/node.sh

The `npm` binary built when fetching node has been broken for a long time.
Fixes #6356

Wrap the npm binary to use the correct node.js

---

admin/build.sh

This should fix the `[[: not found` issue (https://github.com/rethinkdb/rethinkdb/issues/6358#issuecomment-300606330)

Add missing shebang to admin/build.sh

---

src/clustering/administration/jobs/manager.cc
src/pprint/js_pprint.cc
src/pprint/js_pprint.hpp
src/pprint/pprint.cc
src/pprint/pprint.hpp
src/rdb_protocol/func.cc
src/unittest/pprint_test.cc

This refactors the pretty print logic.

Refactor pretty print code.

---

mk/packaging.mk
mk/support/pkg/npm-pkg.inc

* Removes `--no-registry` when invoking `npm` (backported from 2.4)
* Forces using GCC 5 on Zesty (like we already do on Yakkety)

Support for packaging Ubuntu Zesty

---

NOTES.md

The formatting of Server/Packaging sections did not render properly in GitHub Markdown.
Additionally, I'm assuming the improved compatibility for Chrome was indeed Chrome 58, which was very recently released, and not Chrome 48, which was released Jan 2016.

Fix typos in 2.3.6 Release Notes

---

src/clustering/administration/auth/permissions.cc

When conversion from boost optional to homegrown optional was done an existence gaurantee check was changed to a truthy check which causes a crasher.

Fix auth permissions bug

---

src/rdb_protocol/real_table.cc
src/unittest/rdb_interruptor.cc

This fixes the disabled interrupt tests that were causing segfaults. The segfaults occurs because the unit test environment doesn't currently mock the `table_meta_client_t` so a get write hook causes a null pointer dereference and crashes the process.
Mocking the `table_meta_client_t` looked extremely extensive so instead I opted to alter the get_write_hook method to exit early if ignoring write hooks which prevents the nullptr from being used.
Addresses #6095

Fix interrupt tests #6095

---

test/rql_test/src/changefeeds/now.py_one.yaml

This removes an obsolete test that is no longer needed due to restored determinism in r.now for change feeds.

Remove obsolete change feed test

---

test/rql_test/interface/rethinkdb_jobs.py_one.test

This can sometimes be flaky causing tests to fail

Remove host checks from jobs table tests

---

mk/support/pkg/node.sh

Downgrades node to 6.11.0, which is what it had previously been in v2.4.x and next.
This avoids the ENOENT issues on Ubuntu 17.04, and also v2.4.x and next.

Fix bluebird ENOENT issues, bring node back to 6.11.0.

---

src/unittest/timer_test.cc

We cannot use std::make_unique yet, apparently.
We're building with C++11 or gnu++11.  Probably old platforms still want this.

Fix timer_test build problem

---

src/containers/lru_cache.hpp
src/rdb_protocol/terms/string.cc
src/unittest/lru_cache_test.cc

Fixes #6202.  Replaces #6203.  This is basically the fix pushed in #6207.

Revamp LRU cache

---

mk/packaging.mk

Tweaks the build-deb so that it works for stretch on v2.3.x.

Fix build-deb for stretch

---

src/rdb_protocol/pseudo_time.cc
src/rdb_protocol/pseudo_time.hpp
src/rdb_protocol/terms/time.cc

Make r.iso8601 round, not truncate.

---

mk/README.md
mk/main.mk

Adds back a basic 'make test' target, thanks to @lbguilherme's comment in #6582.  People might need help finding out how to run tests, otherwise.
Left out the options and such, to avoid bloat.

Add basic 'make test' target.

---

packaging/assets/init/rethinkdb

**This limit caused our production database to take an epic downtime during heavy load.** Whenever restarted, it would fail because it would not be able to accept clients. Our application keeps a connection pool limited to 6K connections. By default the limit is only 4K connections, which is not ok for a production system.
Fixes #4447 and #5302

Increase limit of open files for init.d script

---

src/rdb_protocol/btree_store.cc
src/rdb_protocol/store.cc
src/rdb_protocol/store.hpp
src/unittest/btree_sindex.cc
src/unittest/rdb_btree.cc

…ffecting changefeed limit queries
Fixes a bug where a so-called "superblock" gets released too early.  Affects behavior of limit change feeds defined on secondary indexes.
This might fix issue #6695.

Fix limit change feed secondary index bug

---

.gitignore
admin/build.mk
admin/generate.sh
configure
drivers/build.mk
mk/README.md
mk/main.mk
mk/packaging.mk
mk/paths.mk
mk/rethinkdb.vcxproj.xsl
mk/windows.mk
src/build.mk

Removes the notion of precompiled web assets.  (They're always precompiled now.)
Ports dac34e7a1dfc7f1d27076a338d94c119a527ba92 to v2.4.x branch.

Use pre-generated src/gen/web_assets.cc

---

README.md

The `libssl-dev` package is not listed for install but needed for the builds.

Add libssl-dev

---

drivers/python/rethinkdb/ast.py

```
>>> reload(rethinkdb.ast)
<module 'rethinkdb.ast' from 'rethinkdb/ast.py'>
>>> from rethinkdb.ast import ReQLDecoder
>>> ReQLDecoder().convert_time({"epoch_time": 500})
datetime.datetime(1970, 1, 1, 0, 0, 0, 500000)
>>> ReQLDecoder().convert_time({"epoch_time": 500, "timezone": "00:00"})
datetime.datetime(1970, 1, 1, 0, 0, 0, 500000, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x10eb26590>)
>>> ReQLDecoder().convert_time({"epoch_time": 500, "timezone": "-05:00"})
datetime.datetime(1970, 1, 1, 0, 0, 0, 500000, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x10eb26750>)
>>> ^D
```
Fixes #5801 by applying a slightly modified form of the original patch. Tested on Python 2.X to ensure backwards compatibility.

Apply patch for rethinkdb/rethinkdb#5801

---

.gitignore
admin/build.mk
admin/generate.sh
configure
drivers/build.mk
mk/README.md
mk/main.mk
mk/packaging.mk
mk/paths.mk
mk/rethinkdb.vcxproj.xsl
mk/windows.mk
src/build.mk

Reapplies old commit, with some hacky patching for getting the debian/ubuntu package builds working.
This way npm, admin-deps, and whatnot, is not a true dependency, which means that macOS builds are now working again.

Use pregenerated web_assets.cc checked into src directory (again)

---

src/unittest/timer_test.cc

Includes math.h in a unittest file to fix macOS build (after recent include simplification).  On Linux, I suppose some other system header brings it in.

Fix macOS build, including math.h

---

test/rql_test/src/meta/grant.yaml

The `test_user` as the value of `user` would be a variable, but we need this as a string since this is the user's name. By fixing this issue, we resolve "some" failing unit tests for the java client

Use "test_user" with quotations

---

drivers/javascript/net.coffee
drivers/javascript/package.json

With the 2.4.0 version of the driver, it is not possible to override the default host and port. Because this is needed in some cases, we need to support this behavior.
Because of the promises, the output is the following: The error is related to port 1234, the two success log lines are related to the first and last connection test.

Fix default port and host overrides

---

src/clustering/administration/logs/log_writer.cc

This was introduced in 2.4.0 after a refactor switched away from the
write(2) syscall.  This forces flushing when stdout isn't on a TTY.
Fixes #6819.

Actually fflush after calling fwrite in logging

---

admin/static/coffee/modals.coffee
admin/static/coffee/ui_components/modals.coffee
admin/static/handlebars/error_input.hbs

When creating a new table or database with a hyphen in the name using the admin UI, the following error message is shown:
> You can only use alphanumeric characters and underscores for a table's name.
Allow hyphens in table and database names.
**Code examples**
N/A
**Checklist**
**References**
resolves https://github.com/rethinkdb/rethinkdb/issues/6828

Allow hyphens in table and database names

---

src/config/args.hpp

"If anybody wants to make a pull request updating MAX_THREADS to 260 (from 128) in RethinkDB's v2.4.x and next branches, it would be much appreciated.  Due to some temporary contract issues I can 99% do that now, but just to keep copyright squeaky clean, somebody else should." - srh

MAX_THREADS bumped to 260, part 2 of 2

---

src/config/args.hpp

"If anybody wants to make a pull request updating MAX_THREADS to 260 (from 128) in RethinkDB's v2.4.x and next branches, it would be much appreciated.  Due to some temporary contract issues I can 99% do that now, but just to keep copyright squeaky clean, somebody else should." - srh

MAX_THREADS bumped to 260, part 1 of 2

---

README.md

The Elixir driver has been forked and is now available under rethinkdb/rethinkdb-elixir.
**Checklist**

docs: Use URL rethinkdb/rethinkdb-elixir

---

src/rdb_protocol/datum.cc

👋  adding a patch for osx builds (see https://github.com/Homebrew/homebrew-core/pull/59643 and https://github.com/Homebrew/homebrew-core/pull/67782)

fix: patch for rethinkdb 2.4.1 osx build

---

scripts/generate_serialize_macros.py

Fixes issues in #6884 
Python3 removed xrange, use range instead.  Fix some incorrect bracket placement.
**Checklist**
The reason for no v2.4.x PR,
v2.4.x builds nodejs 6.11.0 which requires python2. whereas next branch does not build nodejs by default.

Fix for python3 scripts

---

mk/support/pkg/patch/v8_4-gcc6+.patch

Like https://github.com/rethinkdb/rethinkdb/pull/6963 but for v2.4 branch

Patch v8 build arguments for gcc6+ support (v2.4)

---

mk/support/pkg/patch/v8_4-gcc6+.patch

Pass `-fno-delete-null-pointer-checks` to prevent segmentation fault with `mksnapshot`.
It fixes issues: https://github.com/rethinkdb/rethinkdb/issues/5757, https://github.com/rethinkdb/rethinkdb_rebirth/issues/59, https://github.com/rethinkdb/rethinkdb/issues/6731  
Since gcc6, it was no longer possible to build rethinkdb and especially this old v8 version. By preventing this compiler optimization, it builds (tested with gcc10.2 and it runs smoothly).
**Checklist**
**References**
Some interesting references:  
- https://bugs.archlinux.org/task/49395
- https://github.com/qt/qtwebengine-chromium/commit/d03c8ccab741952fee6bd54fb56a878c7cc4ca97
- https://github.com/arangodb/arangodb/issues/1817

Patch v8 build arguments for gcc6+ support

---

src/build.mk

Apparently with QuickJS's build system, with LTO, you get a warning that `@` is unused because the makefile expands `@F` outside of a rule.  See https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html .
That's broken, and to avoid that, I'm silencing the warning an disabling LTO.

Update QuickJS vendored repo build system logic and point to non-LTO/non-warning vendored commit

---

src/random.cc
src/thread_local.hpp

#6957 would need to be applied to v2.4.x.
Also, it makes the mistake of avoiding the NOINLINE macros.  We have thread locals using the peculiar TLS_... macros because our coroutines can switch POSIX threads and basic thread_local usage could cause the compiler to optimize access to the variables such that a second access is assumed to be on the same thread as the first access.  An explanation exists in thread_local.hpp.
So now thread_local.hpp is updated to have TLS_with_get_ref, to support noncopyable thread locals and returning them by reference.

Apply fixed version of "try to fix memory leak" to v2.4.x

---

src/clustering/immediate_consistency/history.hpp
src/crypto/random.hpp

I got some compilation fails recently on Ubuntu 20.04 with clang++-9, this is a fix.
Add a missing header and namespace.
**Checklist**

Fix build on Ubuntu 20.04 with clang++-9

---

src/extproc/http_job.cc

Addresses #6968 .  This is less work than implementing http/2 parsing, or for that matter, figuring out what RethinkDB is doing its own parsing for instead of using some curl facility.
**Checklist**

Force r.http requests to use http/1.1

---

src/rdb_protocol/btree_store.cc
src/rdb_protocol/store.cc
src/rdb_protocol/store.hpp
src/unittest/btree_sindex.cc
src/unittest/rdb_btree.cc

The PR backports the fix described in https://github.com/rethinkdb/rethinkdb/pull/6710 to the 2.3.x branch, to attempt mitigation of https://github.com/rethinkdb/rethinkdb/issues/6863

Backport 'Treat release_superblock properly in do_read' to 2.3.x

---

src/cjson/cJSON.cc
src/clustering/administration/auth/scram_authenticator.cc
src/clustering/administration/main/command_line.cc
src/clustering/administration/persist/file.cc
src/http/http_parser.cc
src/rapidjson/document.h
src/rdb_protocol/changefeed.cc
src/rdb_protocol/geo/s2/util/endian/endian.h

The saslname_decode bug was found while addressing GCC warnings.
**Checklist**

Fix saslname_decode logic in =2C and =3D escaping, and some GCC warnings

---

src/arch/runtime/event_queue/poll.cc
src/rapidjson/document.h
src/rdb_protocol/datum_stream.cc
src/rdb_protocol/geo/s2/util/math/vector3-inl.h
src/rdb_protocol/geo/s2/util/math/vector3.h
src/rdb_protocol/term_storage.hpp

Different opinions about unused variables, and a new warning about copy ctor/copy assignment consistency, the code being deprecated in the C++ standard.
**Checklist**

Fix more GCC warnings

---

src/btree/internal_node.cc
src/btree/leaf_node.cc
src/extproc/js_job.cc
src/unittest/internal_node_test.cc

This seems to be the last of the new GCC warnings seen in Debian Bullseye.
**Checklist**

Silence more GCC warnings

---

src/build.mk

Avoids the use of `git -C`, for compatibility with older git versions like the one available on CentOS 7.
Note that the CentOS 7 build is still failing because it doesn't have C11 support, which QuickJS is using (at least by default), expecting stdatomic.h to exist.

Revert QuickJSpp, avoid git -C

---

src/build.mk

(because we un-integrated that).
Fixes the build

Remove quickjs-version.h build step integrated for quickjspp

---

src/build.mk

Unconfigures Worker and Atomic features from QuickJS, so that stdatomic.h is not #included.
With this change, we successfully build on CentOS 7.  (We run into a package generation problem, but compilation works.)
**Checklist**

Point to vendored submodule without stdatomic.h usage

---

mk/support/pkg/patch/quickjs_1-no-atomics.patch
mk/support/pkg/patch/quickjs_2-no-workers.patch
mk/support/pkg/quickjs.sh
scripts/build-rpm.sh

Makes build-rpm.sh fetch explicitly which deps it wants to statically link.
Also, makes us only build libquickjs.a, not the entire quickjs "make install" (hence, "make all") target, and disables a couple of exotic QuickJS features: workers and atomics.  This gets building for CentOS 7 users working.  It also gets Ubuntu Trusty and Debian Jessie package building working.
JS workers and atomics were disabled with the intent to get the build to succeed, but it's also desirable on its own to have that disabled.
**Checklist**

build-rpm.sh script updates, CentOS 7 support

---

src/clustering/administration/persist/raft_storage_interface.cc

As far as I can tell, raft log indexes could never actually make it past 32 bits.  Good thing they move relatively slowly.
This fixes #7036.
**Checklist**

Avoid use of 32-bit int str_to_log_index

---

mk/support/pkg/openssl.sh

Gets us building on MacOS on ARM.
Generally, `./configure --fetch all PYTHON=/usr/bin/python3` or `./configure --allow-fetch PYTHON=/usr/bin/python3` followed by `make -j8` or `make -j8 DEBUG=1` successfully build.
I verified that the admin UI started up and you could run queries, including r.http.
We encounter #7041 though.
**Checklist**

Fix MacOS ARM build

---

src/unittest/disk_conflict_resolution.cc

Fixes #7042.  It was a problem with the unit test.
**Checklist**

Make DiskConflictTest tests run in thread pool

---

src/unittest/extproc_test.cc

It's unclear why I disabled it in 2018.  It is the only disabled unit test, and it is passing.
**Checklist**

Un-disable ExtProc.CrashedJob test

---

src/errors.hpp
src/rethinkdb_backtrace.cc

One thing to note: it's not _always_ working.  E.g. it doesn't work if we have a SIGSEGV but it does if we have guarantee(false).  It probably has something to do with signal handling.
We also encountered the confusing situation in `crash_or_trap` where `raise(SIGTRAP)` didn't abort the process.  Maybe it is now swallowed up by MacOS.  So now the crash_or_trap macro is the same as crash -- it calls abort() after the BREAKPOINT line.
If you're running a debugger on some system and want to do something crazy like step forward, well, then, you can adjust the macro accordingly.
I assume the reason for this MacOS change is somehow related to how we block signals on non-main threads in thread_pool.cc.  Maybe we just ignore SIGTRAP now on MacOS.  It didn't trap when running in lldb either.
(I …

Get MacOS rethinkdb_backtrace, make crash_or_trap abort()

---

src/backtrace.cc
src/rethinkdb_backtrace.cc

Add CXXFLAGS=-DRDB_NO_BACKTRACE to your ./configure line, or your
environment when running make.
I have not (yet?) tested this on Alpine or with Musl libc.  (In the prior month or two, I got reliance on backtrace() being the one error on Alpine.)  This will make it possible or at least easier for musl users to use RethinkDB.

Add RDB_NO_BACKTRACE flag for musl, alpine users

---

src/backtrace.cc
src/backtrace.hpp

and some other now unnecessary-to-compile code
This fixes more linker errors in alpine under musl.
We now compile under alpine (`make DEBUG=1` has been tested, at least).

Comment out backtrace_symbols with RDB_NO_BACKTRACE

---

CONTRIBUTING.md
README.md

I took the questionable liberty of reformatting the paragraphs to use fixed widths...
Somebody might want to view the files in a text editor
Updates the CONTRIBUTING.md with instructions to point to the `old_admin` branch:
https://github.com/rethinkdb/rethinkdb/tree/old_admin
which is where the admin UI generation branch is now officially located.

old_admin_readme, generate v2.4.2 web assets

---

src/paths.cc
src/random.cc

This PR resolves https://github.com/rethinkdb/rethinkdb/issues/4647 by using `fail_due_to_user_error` over `guarantee_err` and `guarantee_winerr` for `remove_directory_helper`.

refactor: avoid backtrace for user error

---

src/clustering/administration/main/command_line.cc

Per https://github.com/rethinkdb/rethinkdb/issues/7061#issuecomment-1119384833, added help text warning about using `--initial-password` cli option and suggesting `--config-file` as an alternative.

Add warning about using `--initial-password` to cli help text

---

.gitignore
admin/static/coffee/body.coffee

Fixes https://github.com/rethinkdb/rethinkdb/issues/7068 by passing the missing var to the template. The release notes will always point to the give version tag's `NOTES.md` for the sake of simplicity.
cc: @srh

fix: pass release notes link to template

---

.github/actions/driver-tests/action.yml
.github/actions/tests/action.yml
.github/workflows/build.yml
test/common/utils.py
test/full_test/disabled.group
test/rql_test/drivers/driver.py
test/rql_test/importRethinkDB.js
test/rql_test/importRethinkDB.rb
test/rql_test/src/arity.yaml
test/rql_test/src/control.yaml
test/rql_test/src/meta/grant.yaml
test/rql_test/test-runner

resolves https://github.com/rethinkdb/rethinkdb/issues/6871
This PR is a follow-up on the approach introduced at https://github.com/rethinkdb/rethinkdb/pull/7058. We add the following tests to the pipeline grouped as follows:
* Unit tests
* Integration tests
* [bonus_tests.test](https://github.com/rethinkdb/rethinkdb/blob/v2.4.x/test/full_test/bonus_tests.test)
* [changefeeds.test](https://github.com/rethinkdb/rethinkdb/blob/v2.4.x/test/full_test/changefeeds.test)
* [clustering.test](https://github.com/rethinkdb/rethinkdb/blob/v2.4.x/test/full_test/clustering.test)
* [continuous.test](https://github.com/rethinkdb/rethinkdb/blob/v2.4.x/test/full_test/continuous.test)
* [error_tolerant.test](https://github.com/rethinkdb/rethinkdb/blob/v2.4.x/test/full_test/error_tolerant.test)
* …

Add polyglot and integration tests to CI/CD

---

mk/rethinkdb.vcxproj.xsl
mk/support/pkg/quickjs.sh

Fixed the Windows build, which was broken by #7060.  This branch become broken when its PR's that added Windows support got rebased.
Also, this points to a stripped down release of quickjspp.  It includes some bug fixes in https://github.com/bellard/quickjs that come after the most recent release.  Generally it has fewer commits than c-smile's quickjspp, omitting the JSX and storage code, and a couple of minor adjustments.

Fix windows build and point to stripped down quickjspp

---

README.md

The tbolier driver is incomplete, according to its [roadmap](https://github.com/tbolier/php-rethink-ql/blob/master/docs/roadmap.md),
and a quick perusal of the codebase.
There is some discussion at https://github.com/rethinkdb/rethinkdb/commit/327e8aace86fd132a27c48e6dbca935a3a9679d1
@tbolier
@ForbiddenEra

Switch PHP driver in README back to danielmewes' php-rql

---

STYLE.md

Shortens the document so that open source contributors have less to read.
Removes:
- commit message sniping
- generally applicable C++ practices
- excessively specific style rules
Keeps:
- project-specific practices

Simplify STYLE.md

---

src/backtrace.cc
src/client_protocol/server.cc
src/clustering/administration/metadata.hpp
src/rpc/semilattice/joins/versioned.hpp
src/serializer/translator.cc

kodehawa reports this build error on Arch (Linux?):
```
In file included from ./src/clustering/administration/tables/database_metadata.hpp:14:
./src/rpc/semilattice/joins/versioned.hpp:96:43: error: use of undeclared identifier 'time'
timestamp = std::max(timestamp+1, time(nullptr));
```

Include <time.h> in files using time function

---

Makefile
configure
mk/check-env.mk
packaging/osx/uninstall.scpt
scripts/gen-version.sh

Allegedly it is getting obsolete -- ArchLinux is complaining.
Our package dependencies use it, but this does not touch that.

Replace some egrep uses

---

src/clustering/administration/main/options.cc

This keeps help formatting from getting cramped over on the right edge by over-long syntax descriptions.  Also, this keeps the help information, which is clamped to at least 30 characters in width, from overflowing past column 80.  For long syntax descriptions, this puts the help description on the next line.
Before:
After:

Improve general help formatting

---

mk/support/pkg/openssl.sh

Updates the version.  See https://www.openssl.org/blog/blog/2022/11/01/email-address-overflows/ .

Update openssl version (if fetched and statically linked) to 3.0.7

---

src/arch/runtime/context_switching.hpp
src/backtrace.cc
src/clustering/administration/auth/authentication_error.hpp
src/errors.hpp
src/utils.hpp

This adds some stdint.h includes in response to a user report of compilation failure.  The include in errors.hpp is added to generally help reduce the risk of this problem in the future.
It also adds an RDB_NO_BACKTRACE preprocessor conditional around the execinfo.h include.

Some stdint.h include-what-you-use for alpine/musl

---

src/btree/internal_node.cc
src/btree/internal_node.hpp
src/btree/leaf_node.cc
src/btree/node.hpp
src/buffer_cache/blob.cc
src/buffer_cache/blob.hpp
src/containers/unaligned.hpp
src/repli_timestamp.hpp

This is a best effort fix to avoid some unaligned memory accesses that have cropped up in testing 32-bit ARM code.  This avoids crashes that occur when running 32-bit ARM binaries on a 64-bit kernel.
This will probably improve the performance of 32-bit ARM on a 32-bit Linux kernel, because supposedly the kernel traps the error and fixes up the memory read.  Or so I've read.  That could matter if anybody has that running on some rPi somewhere.
I checked by disassembly -- this does not affect x86-64 code generation on g++, except maybe for copy() calls in debug mode -- nor would we expect it to.
With this fix I got 32-bit ARM debug binaries to run successfully on a 64-bit ARM system.
For what it's worth, I ran into some unrelated issue with release binaries, possibly some sort of …

Avoid some bus erroring unaligned memory accesses.

---

admin/build.mk
scripts/compile-web-assets.py

This generates the web_assets.cc with its map sorted by file path in alphabetic order, instead of the machine's local directory traversal order.
This makes the output repeatable, with smaller diffs.  Fixes #7133.
Also, we make the "double-check version" output of `make generate`, used to assure the user the final output of the version number was generated correctly, be less sensitive to line wrapping of the preceding rethinkdb-version string, so that it functions more correctly.

Generate web_assets.cc in consistent order

---

NOTES.md
src/arch/io/disk/filestat.cc

Compilation had broken on the Alpine linux edge version, using musl instead of glibc.  Further investigation shows that using fstat64 is unnecessary.  We do set `_FILE_OFFSET_BITS` to 64 in the CXXFLAGS.
Compilation has been tested on i386 and amd64 Alpine 3.15-3.18 and Alpine Edge, as well as on i386 Ubuntu 14.04.

Avoid fstat64, which is unnecessary

---

src/rdb_protocol/datum.cc
src/rdb_protocol/datum.hpp
src/rdb_protocol/error.cc
src/rdb_protocol/error.hpp
src/rdb_protocol/func.cc

Some small improvements to reql error macros.
When RQL_ERROR_BT is not defined, this prevents us from passing unnecessary, unused parameters to runtime_fail.  Also we use a move constructor in some places.
RQL_ERROR_BT is not defined in release mode.
This should minimally improve performance, when certain reql errors happen, or when there is code that throws and catches errors.

Reql error improvements

---

src/cjson/cJSON.cc

This PR fixes a **buffer overflow vulnerability** in the `parse_string` function within the **cJSON** library. The issue arises when parsing **UTF-16 surrogate pairs** in JSON strings, where the buffer allocated may not be large enough to accommodate the converted UTF-8 characters. This causes **memory corruption** and potential **arbitrary code execution**.
This fix includes:
1. **Bounds Checking**: Adds proper validation of buffer sizes using an end pointer.
2. **Unicode Validation**: Additional checks for Unicode characters, especially **surrogate pairs**.
3. **Memory Cleanup**: Ensures the valuestring is properly assigned early to prevent memory leaks.
4. **Improved Error Handling**: Enhances error handling to mimic security patches from the original cJSON library.
This vulnerability …

Fix: Buffer Overflow Vulnerability in cJSON String Parsing Function

---

configure
src/arch/runtime/context_switching.cc
src/rapidjson/allocators.h
src/rpc/connectivity/cluster.cc

This PR adds support for the riscv64 architecture to RethinkDB.
- Updated `configure` script to detect and handle riscv64 as a supported platform.
- Extended architecture-specific logic in `src/arch/runtime/context_switching.cc` to include riscv64, enabling proper context switching and runtime support.
- Adjusted `src/rapidjson/allocators.h` and `src/rpc/connectivity/cluster.cc` for riscv64 compatibility.
- Ensured all new code paths are conditionally compiled and do not affect existing supported architectures.
RISC-V is an open and rapidly growing CPU architecture. Adding riscv64 support enables RethinkDB to run natively on RISC-V hardware, broadening its usability and aligning with the project's goal of wide platform compatibility.
- Successfully built and ran RethinkDB on a **Sophgo …

feature: add RISC-V architecture support
